services:
  ollama:
    build:
      context: .
      dockerfile: docker/Dockerfile.ollama
    ports:
      - "11435:11434"
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    depends_on:
      - ollama
    ports:
      - "8000:8000"

