
FROM python:3.12-slim
RUN apt-get update && apt-get install -y --no-install-recommends build-essential gcc libxml2-dev libxslt1-dev libffi-dev curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app /app/app
COPY start-api.sh /app/start-api.sh
RUN chmod +x /app/start-api.sh
EXPOSE 8000
